name: continuous-integration

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  lint-and-publish-bicep:
    uses: ./.github/workflows/lint-and-publish-bicep.yml
    
  python-tests:
    uses: ./.github/workflows/python-tests.yml
    with:
      paths: '["tests/data_generator"]'