name: continuous-delivery

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - infra/**

  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  lint-and-publish-bicep:
    uses: ./.github/workflows/lint-and-publish-bicep.yml

  validate-bicep:
    needs:
      - set-build-variables
      - lint-and-publish-bicep
    uses: ./.github/workflows/validate-bicep.yml
    with:
      ENVIRONMENT: Test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ format('{0}-aifjmp-{1}-{2}', github.ref_name, github.run_number, github.run_id) }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  
  test-template:
    needs:
      - set-build-variables
      - validate-bicep
    strategy:
      matrix:
        include:
          - name: network-isolated
            AZURE_NETWORK_ISOLATION: 'true'
          - name: public
            AZURE_NETWORK_ISOLATION: 'false'
    name: Test Template (${{ matrix.name }})
    uses: ./.github/workflows/test-template.yml
    with:
      ENVIRONMENT: Test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ format('{0}-aifjmp-{1}-{2}-{3}', github.ref_name, github.run_number, github.run_id, matrix.name) }}
      AZURE_NETWORK_ISOLATION: ${{ matrix.AZURE_NETWORK_ISOLATION }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
