name: Continuous Delivery

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths:
      - infra/**
      - src/**
      - tests/**
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
  checks: write
  pull-requests: write

jobs:
  set-build-variables:
    name: Set Build Variables
    uses: ./.github/workflows/set-build-variables.yml

  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml

  e2e-test:
    needs:
      - set-build-variables
      - lint-and-publish-bicep
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: project-public
            AZURE_NETWORK_ISOLATION: 'false'
            DEPLOY_SAMPLE_OPENAI_MODELS: 'true'
            AZURE_AI_FOUNDRY_HUB_DEPLOY: 'false'
          - name: project-isolated
            AZURE_NETWORK_ISOLATION: 'true'
            DEPLOY_SAMPLE_OPENAI_MODELS: 'false'
            AZURE_AI_FOUNDRY_HUB_DEPLOY: 'false'
          - name: hub-public
            AZURE_AI_FOUNDRY_HUB_DEPLOY: 'true'
            AZURE_NETWORK_ISOLATION: 'false'
            DEPLOY_SAMPLE_OPENAI_MODELS: 'true'
          - name: hub-isolated
            AZURE_AI_FOUNDRY_HUB_DEPLOY: 'true'
            AZURE_NETWORK_ISOLATION: 'true'
            DEPLOY_SAMPLE_OPENAI_MODELS: 'false'

    name: E2E Test (${{ matrix.name }})
    uses: ./.github/workflows/e2e-test.yml
    with:
      ENVIRONMENT: Test
      BUILD_VERSION: ${{ needs.set-build-variables.outputs.BUILD_VERSION }}
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
      AZURE_ENV_NAME: ${{ format('aifj-{0}-{1}', matrix.name, github.run_id) }}
      AZURE_NETWORK_ISOLATION: ${{ matrix.AZURE_NETWORK_ISOLATION }}
      DEPLOY_SAMPLE_OPENAI_MODELS: ${{ matrix.DEPLOY_SAMPLE_OPENAI_MODELS }}
      AZURE_AI_FOUNDRY_HUB_DEPLOY: ${{ matrix.AZURE_AI_FOUNDRY_HUB_DEPLOY }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}