name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  lint-and-publish-bicep:
    name: Lint and Publish Bicep
    uses: ./.github/workflows/lint-and-publish-bicep.yml

  lint-and-test-python-apps:
    name: Lint and Test Python Apps
    uses: ./.github/workflows/lint-and-test-python-apps.yml
    with:
      # List all app names (folders) in /src and /tests that should be tested
      app_names: '["tools/python/data_generator","tools/python/create_ai_search_index"]'