name: lint-and-publish-bicep

on:
  workflow_call:

jobs:
  build-armtemplates:
    name: Lint and Publish Bicep
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Lint Bicep
      run: |
        bicep lint ./infra/main.bicep
  
    - name: Publish hub based project (v1) Bicep as Workflow Artifact
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure_bicep
        path: |
           ./infra/v1/*.bicep
           ./infra/v1/*.json
           ./infra/v1/**/

    - name: Publish Foundry project (v2) Bicep as Workflow Artifact
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure_bicep
        path: |
           ./infra/v2/*.bicep
           ./infra/v2/*.json
           ./infra/v2/**/
