name: Lint and Publish Bicep

on:
  workflow_call:

jobs:
  build-armtemplates:
    name: Lint and Publish Bicep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Bicep
        run: |
          bicep lint ./infra/main.bicep

      - name: Spellcheck Bicep files
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.bicep"
          config: ".cspell.json"

      - name: Publish Bicep as Workflow Artifact
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure_bicep
          path: |
            ./infra/*.bicep
            ./infra/*.json
            ./infra/**/*
