name: python-tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          cd src/data_generator
          python -m pip install --upgrade pip
          python -m pip install -e .[dev]

      - name: Lint with ruff
        run: |
          cd src/data_generator
          python -m ruff check .

      - name: Type check with mypy
        run: |
          cd src/data_generator
          python -m mypy .

      - name: Test with pytest
        run: |
          cd src/data_generator
          python -m pytest tests --cov --cov-report=xml --cov-fail-under=90

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          file: ./src/data_generator/coverage.xml